project:
  type: website
  resources: 
    - "*.mp3"
  output-dir: docs

website:
  favicon: "hansi.jpg"
  title: "Société Alsacienne d'Artisanat de la Data"
  description: "Blog sur les travaux réalisés dans le cadre de la data"
  navbar:
    logo: "hansi.jpg"
    right:
      - text: Journal
        href: blog.qmd 
      - icon: github
        href: https://github.com/ledemocrate
sidebar:
  contents:
    - section: "Articles"
      contents: posts

blog:
  categories: true
  listing: true

format:
  html:
    theme: litera
    css: styles.css



