project:
  type: website
  resources: 
    - "*.mp3"
  output-dir: docs

website:
  favicon: "hansi.jpg"
  title: "Société Alsacienne d'Artisanat de la Data"
  description: "Blog sur les travaux réalisés dans le cadre de la data"
  navbar:
    logo: "hansi.jpg"
    right:
      - text: Journal
        href: blog.qmd 
      - icon: github
        href: https://github.com/ledemocrate
      - icon: reddit
        href: https://www.reddit.com/user/goldentzgrahams
      - icon: linkedin
        href: https://www.linkedin.com/in/quentin-gollentz-697993172/
      - icon: playstation
        href: https://www.playstation.com/fr-fr/playstation-network/
        
format:
  html:
    theme: litera
    css: styles.css



