---
title: "Tidytuesday 03-03-2026 : ??"
categories: ['Nettoyage des données','Analyse des données']
tags: ['data-science', 'r', 'python', 'pgvector']
author:
    name: GOLLENTZ Quentin
#    url: https://www.linkedin.com/in/quentin-gollentz-697993172/
    email: quentin.gollentz@outlook.com
date: last-modified
date-format: "DD-MM-YYYY"
description: "Traitement des données du 03-03-2026"
title-block-banner: "#ECF4FA"
format: 
  html:
    code-fold: true
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
    html-math-method: katex
    self_contained: no
editor: 
  markdown: 
    wrap: 72
---

# Chargement des librairies

```{r}
#| warning: false
library(tidyverse)
library(tidytuesdayR)

# Chargement des données

tuesdata <- tt_load('2026-03-03')
```

## Data Dictionary

### `clutch_size_cleaned.csv`

|variable                    |class     |description                           |
|:---------------------------|:---------|:-------------------------------------|
|individual                  |integer   |The ID of the individual. |
|age                         |integer   |The age of the individual. |
|date                        |date      |Date of the record. |
|locality                    |character |Locality. |
|eggs                        |integer   |Number of eggs. |
|body_mass_grams             |integer   |The body mass of the individual in grams. |
|straight_carapace_length_mm |integer   |The carapace length in millimeters. |

### `tortoise_body_condition_cleaned.csv`

|variable                    |class     |description                           |
|:---------------------------|:---------|:-------------------------------------|
|individual                  |character |The ID of the individual. Here it is a character type because some IDs include letters. |
|year                        |integer   |The year the measurement was taken. |
|year_recode                 |integer   |Per-individual observation index: 1 for the first year an individual was observed, 2 for the second, and so on, ordered by year/recapture. |
|season                      |character |Season of the year. |
|locality                    |character |Locality. |
|sex                         |character |Sex. |
|body_mass_grams             |double    |The body mass of the individual in grams. |
|body_condition_index        |double    |The index for the body condition. |
|straight_carapace_length_mm |double    |The carapace length in millimeters. |
