---
title: "Tidytuesday 11-11-2025 : ??"
categories: ['Nettoyage des données','Analyse des données']
author:
    name: GOLLENTZ Quentin
#    url: https://www.linkedin.com/in/quentin-gollentz-697993172/
    email: quentin.gollentz@outlook.com
date: last-modified
date-format: "DD-MM-YYYY"
description: "Traitement des données du 11-11-2025"
title-block-banner: "#ECF4FA"
format: 
  html:
    code-fold: true
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
    html-math-method: katex
    self_contained: no
editor: 
  markdown: 
    wrap: 72
---

# Chargement des librairies

```{r}
#| warning: false
library(tidyverse)
library(tidytuesdayR)

# Chargement des données

tuesdata <- tt_load('2025-11-11')
```

## Data Dictionary

### `who_tb_data.csv`

| variable | class | description |
|:-----------------------|:-----------------------|:-----------------------|
| country | character | Country or territory name |
| g_whoregion | character | WHO region |
| iso_numeric | integer | ISO numeric country/territory code |
| iso2 | character | ISO 2-character country/territory code. Note that Namibia's code ("'NA'") includes single quotes to avoid being encoded as missing |
| iso3 | character | ISO 3-character country/territory code |
| year | integer | Year of observation |
| c_cdr | double | Case detection rate (all forms) \[also known as TB treatment coverage\], percent |
| c_newinc_100k | double | Case notification rate, which is the total of new and relapse cases and cases with unknown previous TB treatment history per 100 000 population (calculated) |
| cfr | double | Estimated TB case fatality ratio |
| e_inc_100k | double | Estimated incidence (all forms) per 100 000 population |
| e_inc_num | integer | Estimated number of incident cases (all forms) |
| e_mort_100k | double | Estimated mortality of TB cases (all forms) per 100 000 population |
| e_mort_exc_tbhiv_100k | double | Estimated mortality of TB cases (all forms, excluding HIV) per 100 000 population |
| e_mort_exc_tbhiv_num | integer | Estimated number of deaths from TB (all forms, excluding HIV) |
| e_mort_num | integer | Estimated number of deaths from TB (all forms) |
| e_mort_tbhiv_100k | double | Estimated mortality of TB cases who are HIV-positive, per 100 000 population |
| e_mort_tbhiv_num | integer | Estimated number of deaths from TB in people who are HIV-positive |
| e_pop_num | integer | Estimated total population number |
